image: alekzonder/puppeteer:latest
stages:
  - build
  - test
cache:
  paths:
    - node_modules/
    - client/node_modules
services:
  - redis:latest
  - mongo
install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - client/node_modules
testing:
  stage: test
  variables:
    NODE_ENV: gitlabci
    PORT: 3000
  script:
    - nohup npm run start &
    - sleep 3
    - npm test
